#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pandas", "tqdm==4.66.4", "requests==2.31.0", "colorama==0.4.6", "pyarrow"]
# ///

from utils.player_functions import get_player_data


def main():
    """
    Main function to retrieve data on Premier League Fantasy
    Football players.
    """
    player_data, history_data = get_player_data()

    history_data.to_parquet("data/player_history_data.parquet")
    player_data.to_parquet("data/current_player_data.parquet")


if __name__ == "__main__":
    main()